from __future__ import annotations

import argparse
from pathlib import Path

if __package__:
    from .system_gmm_certification_registry import (
        REGISTRY_PATH,
        REPOSITORY_ROOT,
        CertificationRegistry,
        load_certification_registry,
    )
else:
    from system_gmm_certification_registry import (
        REGISTRY_PATH,
        REPOSITORY_ROOT,
        CertificationRegistry,
        load_certification_registry,
    )

DRIVER_PATH = REPOSITORY_ROOT / "scripts" / "parity" / "rerun_xtabond2_certification.do"


def render_stata_driver(registry: CertificationRegistry) -> str:
    lines = [
        f"version {registry.stata_syntax_version}",
        "clear all",
        "set more off",
        "",
        "* Generated by scripts/parity/build_xtabond2_certification_driver.py.",
        "* Source: artifacts/parity/xtabond2/system_gmm_certification_specs.json",
        "* Do not edit this file directly.",
        "",
        "args repo",
        'if `"`repo\'"\' == "" {',
        '    display as error "Repository root argument is required."',
        '    display as error "Example: do scripts/parity/rerun_xtabond2_certification.do ."',
        "    exit 198",
        "}",
        "",
        'cd "`repo\'"',
        "",
        "capture log close _all",
        'log using "artifacts/parity/xtabond2/xtabond2_certification_rerun.log", ///',
        "    text replace name(xtabond2_certification)",
        "",
        'display as text "SYSTEMGMMKIT_XTABOND2_RERUN_BEGIN"',
        'display as result "stata_current_date=" c(current_date)',
        'display as result "stata_current_time=" c(current_time)',
        'display as result "stata_version=" c(stata_version)',
        'display as result "stata_flavor=" c(flavor)',
        'display as result "stata_os=" c(os)',
        'display as result "stata_machine_type=" c(machine_type)',
        "",
        "capture noisily which xtabond2",
        "if _rc {",
        '    display as error "xtabond2 is not installed. Run: ssc install xtabond2, replace"',
        "    log close xtabond2_certification",
        "    exit 499",
        "}",
        "",
        "capture noisily which parmest",
        "if _rc {",
        '    display as error "parmest is not installed. Run: ssc install parmest, replace"',
        "    log close xtabond2_certification",
        "    exit 499",
        "}",
        "",
    ]

    for spec_id, config in registry.specifications.items():
        lines.extend(
            [
                f'display as text "SYSTEMGMMKIT_RUNNING={spec_id}"',
                f'do "{config["do_file"].as_posix()}"',
                "",
            ]
        )

    lines.extend(
        [
            'display as text "SYSTEMGMMKIT_XTABOND2_RERUN_COMPLETE"',
            'display as result "stata_current_date=" c(current_date)',
            'display as result "stata_current_time=" c(current_time)',
            "log close xtabond2_certification",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the portable xtabond2 rerun driver.")
    parser.add_argument(
        "--registry",
        type=Path,
        default=REGISTRY_PATH,
        help="Certification registry JSON path.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DRIVER_PATH,
        help="Destination Stata do-file path.",
    )
    args = parser.parse_args()

    registry_path = (
        args.registry if args.registry.is_absolute() else REPOSITORY_ROOT / args.registry
    )
    output_path = args.output if args.output.is_absolute() else REPOSITORY_ROOT / args.output
    registry = load_certification_registry(registry_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_stata_driver(registry), encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
