from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

if __package__:
    from .system_gmm_unbalanced_missing_extension import (
        REPOSITORY_ROOT,
        SOURCE_DATA,
        SOURCE_DATA_REFERENCE,
        ExtensionSpec,
        derive_fixture,
        extension_specs,
    )
else:
    from system_gmm_unbalanced_missing_extension import (
        REPOSITORY_ROOT,
        SOURCE_DATA,
        SOURCE_DATA_REFERENCE,
        ExtensionSpec,
        derive_fixture,
        extension_specs,
    )

MANIFEST = (
    REPOSITORY_ROOT
    / "artifacts"
    / "parity"
    / "xtabond2"
    / "specs"
    / "unbalanced_missing_extension_manifest.json"
)
DRIVER = REPOSITORY_ROOT / "scripts" / "parity" / "rerun_xtabond2_unbalanced_missing.do"


def _relative(path: Path) -> str:
    return path.relative_to(REPOSITORY_ROOT).as_posix()


def _sha256(path: Path) -> str:
    content = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(content).hexdigest()


def render_stata_do(spec: ExtensionSpec) -> str:
    output = _relative(spec.output_dir)
    fixture = _relative(spec.fixture)
    return f'''version 17.0
clear all
set more off

* Generated by scripts/parity/build_xtabond2_unbalanced_missing_extension.py.
import delimited using "{fixture}", clear
xtset id t

capture noisily which xtabond2
if _rc {{
    display as error "xtabond2 is required. Run: ssc install xtabond2, replace"
    exit 499
}}
capture noisily which parmest
if _rc {{
    display as error "parmest is required. Run: ssc install parmest, replace"
    exit 499
}}

quietly findfile xtabond2.ado
local xtabond2_ado_file "`r(fn)'"
tempname xtabond2_ado_handle
file open `xtabond2_ado_handle' using "`xtabond2_ado_file'", read text
file read `xtabond2_ado_handle' xtabond2_ado_header
file close `xtabond2_ado_handle'
local xtabond2_ado_header = strtrim("`xtabond2_ado_header'")

xtabond2 y L.y x w, ///
    gmm(L.y x, lag(2 3) collapse eq(both)) ///
    iv(w, eq(level)) ///
    twostep robust small

local xtabond2_e_version "`e(version)'"
gen byte __systemgmmkit_esample = e(sample)

preserve
keep if __systemgmmkit_esample == 1
keep id t
duplicates drop
sort id t
export delimited using "{output}/stata_sample.csv", replace
restore

preserve
clear
set obs 1
gen str48 spec = "{spec.spec_id}"
gen double stata_nobs = e(N)
gen double stata_n_groups = e(N_g)
gen double stata_n_instruments = e(j)
gen double stata_hansen = e(hansen)
gen double stata_hansen_p = e(hansenp)
gen double stata_hansen_df = e(hansen_df)
gen double stata_sargan = e(sargan)
gen double stata_sargan_p = e(sarganp)
gen double stata_sargan_df = e(sar_df)
gen double stata_ar1_z = e(ar1)
gen double stata_ar1_p = e(ar1p)
gen double stata_ar2_z = e(ar2)
gen double stata_ar2_p = e(ar2p)
gen str20 stata_reported_date = c(current_date)
gen str20 stata_reported_time = c(current_time)
gen double stata_version = c(stata_version)
gen str20 xtabond2_e_version = "`xtabond2_e_version'"
gen str80 xtabond2_ado_header = "`xtabond2_ado_header'"
export delimited using "{output}/stata_diagnostics.csv", replace
restore

parmest, saving("{output}/stata_params.dta", replace)
use "{output}/stata_params.dta", clear
export delimited using "{output}/stata_params.csv", replace
'''


def render_driver(specs: tuple[ExtensionSpec, ...]) -> str:
    lines = [
        "version 17.0",
        "clear all",
        "set more off",
        "",
        "* Generated by scripts/parity/build_xtabond2_unbalanced_missing_extension.py.",
        "args repo",
        'if `"`repo\'"\' == "" {',
        '    display as error "Repository root argument is required."',
        '    display as error "Example: do scripts/parity/rerun_xtabond2_unbalanced_missing.do ."',
        "    exit 198",
        "}",
        'cd "`repo\'"',
        "capture log close _all",
        'log using "artifacts/parity/xtabond2/specs/unbalanced_missing_extension_rerun.log", text replace name(extension)',
        'display as text "SYSTEMGMMKIT_UNBALANCED_MISSING_BEGIN"',
    ]
    for spec in specs:
        lines.extend(
            [
                f'display as text "SYSTEMGMMKIT_RUNNING={spec.spec_id}"',
                f'do "{_relative(spec.do_file)}"',
            ]
        )
    lines.extend(
        [
            'display as text "SYSTEMGMMKIT_UNBALANCED_MISSING_COMPLETE"',
            "log close extension",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    source = pd.read_csv(SOURCE_DATA)
    specs = extension_specs()
    manifest_specs: list[dict[str, object]] = []

    for spec in specs:
        spec.output_dir.mkdir(parents=True, exist_ok=True)
        fixture = derive_fixture(spec.spec_id, source)
        fixture.to_csv(spec.fixture, index=False)
        spec.do_file.write_text(render_stata_do(spec), encoding="utf-8")
        manifest_specs.append(
            {
                "id": spec.spec_id,
                "status": "REGISTERED",
                "fixture": _relative(spec.fixture),
                "fixture_sha256": _sha256(spec.fixture),
                "do_file": _relative(spec.do_file),
                "do_file_sha256": _sha256(spec.do_file),
                "native_runner": "scripts/parity/run_native_unbalanced_missing_extension.py",
                "stata_params": f"{_relative(spec.output_dir)}/stata_params.csv",
                "stata_diagnostics": f"{_relative(spec.output_dir)}/stata_diagnostics.csv",
                "stata_sample": f"{_relative(spec.output_dir)}/stata_sample.csv",
            }
        )

    DRIVER.parent.mkdir(parents=True, exist_ok=True)
    DRIVER.write_text(render_driver(specs), encoding="utf-8")
    manifest = {
        "schema_version": 1,
        "authority": (
            "generation manifest only; certification authority is "
            "artifacts/parity/xtabond2/system_gmm_certification_specs.json"
        ),
        "source_data": SOURCE_DATA_REFERENCE.as_posix(),
        "source_data_sha256": _sha256(SOURCE_DATA),
        "driver": _relative(DRIVER),
        "specifications": manifest_specs,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(specs)} registered fixtures and {DRIVER}")


if __name__ == "__main__":
    main()
