version 17.0
clear all
set more off

* Generated by scripts/parity/build_xtabond2_certification_driver.py.
* Source: artifacts/parity/xtabond2/system_gmm_certification_specs.json
* Do not edit this file directly.

args repo
if `"`repo'"' == "" {
    display as error "Repository root argument is required."
    display as error "Example: do scripts/parity/rerun_xtabond2_certification.do ."
    exit 198
}

cd "`repo'"

capture log close _all
log using "artifacts/parity/xtabond2/xtabond2_certification_rerun.log", ///
    text replace name(xtabond2_certification)

display as text "SYSTEMGMMKIT_XTABOND2_RERUN_BEGIN"
display as result "stata_current_date=" c(current_date)
display as result "stata_current_time=" c(current_time)
display as result "stata_version=" c(stata_version)
display as result "stata_flavor=" c(flavor)
display as result "stata_os=" c(os)
display as result "stata_machine_type=" c(machine_type)

capture noisily which xtabond2
if _rc {
    display as error "xtabond2 is not installed. Run: ssc install xtabond2, replace"
    log close xtabond2_certification
    exit 499
}

capture noisily which parmest
if _rc {
    display as error "parmest is not installed. Run: ssc install parmest, replace"
    log close xtabond2_certification
    exit 499
}

display as text "SYSTEMGMMKIT_RUNNING=system_gmm_baseline_controls"
do "artifacts/parity/xtabond2/system_gmm_xtabond2_parity.do"

display as text "SYSTEMGMMKIT_RUNNING=system_gmm_no_controls"
do "artifacts/parity/xtabond2/specs/system_gmm_no_controls/system_gmm_no_controls.do"

display as text "SYSTEMGMMKIT_RUNNING=system_gmm_three_way_controls"
do "artifacts/parity/xtabond2/specs/system_gmm_three_way_controls/system_gmm_three_way_controls.do"

display as text "SYSTEMGMMKIT_RUNNING=system_gmm_decomposition_controls"
do "artifacts/parity/xtabond2/specs/system_gmm_decomposition_controls/system_gmm_decomposition_controls.do"

display as text "SYSTEMGMMKIT_XTABOND2_RERUN_COMPLETE"
display as result "stata_current_date=" c(current_date)
display as result "stata_current_time=" c(current_time)
log close xtabond2_certification
