version 17.0
clear all
set more off

* Generated by scripts/parity/build_xtabond2_unbalanced_missing_extension.py.
args repo
if `"`repo'"' == "" {
    display as error "Repository root argument is required."
    display as error "Example: do scripts/parity/rerun_xtabond2_unbalanced_missing.do ."
    exit 198
}
cd "`repo'"
capture log close _all
log using "artifacts/parity/xtabond2/specs/unbalanced_missing_extension_rerun.log", text replace name(extension)
display as text "SYSTEMGMMKIT_UNBALANCED_MISSING_BEGIN"
display as text "SYSTEMGMMKIT_RUNNING=system_gmm_unbalanced_panel"
do "artifacts/parity/xtabond2/specs/system_gmm_unbalanced_panel/system_gmm_unbalanced_panel.do"
display as text "SYSTEMGMMKIT_RUNNING=system_gmm_variable_missing"
do "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/system_gmm_variable_missing.do"
display as text "SYSTEMGMMKIT_UNBALANCED_MISSING_COMPLETE"
log close extension
