version 17.0
clear all
set more off

* Generated by scripts/parity/build_xtabond2_unbalanced_missing_extension.py.
import delimited using "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/fixture.csv", clear
xtset id t

capture noisily which xtabond2
if _rc {
    display as error "xtabond2 is required. Run: ssc install xtabond2, replace"
    exit 499
}
capture noisily which parmest
if _rc {
    display as error "parmest is required. Run: ssc install parmest, replace"
    exit 499
}

quietly findfile xtabond2.ado
local xtabond2_ado_file "`r(fn)'"
tempname xtabond2_ado_handle
file open `xtabond2_ado_handle' using "`xtabond2_ado_file'", read text
file read `xtabond2_ado_handle' xtabond2_ado_header
file close `xtabond2_ado_handle'
local xtabond2_ado_header = strtrim("`xtabond2_ado_header'")

xtabond2 y L.y x w, ///
    gmm(L.y x, lag(2 3) collapse eq(both)) ///
    iv(w, eq(level)) ///
    twostep robust small

local xtabond2_e_version "`e(version)'"
gen byte __systemgmmkit_esample = e(sample)

preserve
keep if __systemgmmkit_esample == 1
keep id t
duplicates drop
sort id t
export delimited using "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/stata_sample.csv", replace
restore

preserve
clear
set obs 1
gen str48 spec = "system_gmm_variable_missing"
gen double stata_nobs = e(N)
gen double stata_n_groups = e(N_g)
gen double stata_n_instruments = e(j)
gen double stata_hansen = e(hansen)
gen double stata_hansen_p = e(hansenp)
gen double stata_hansen_df = e(hansen_df)
gen double stata_sargan = e(sargan)
gen double stata_sargan_p = e(sarganp)
gen double stata_sargan_df = e(sar_df)
gen double stata_ar1_z = e(ar1)
gen double stata_ar1_p = e(ar1p)
gen double stata_ar2_z = e(ar2)
gen double stata_ar2_p = e(ar2p)
gen str20 stata_reported_date = c(current_date)
gen str20 stata_reported_time = c(current_time)
gen double stata_version = c(stata_version)
gen str20 xtabond2_e_version = "`xtabond2_e_version'"
gen str80 xtabond2_ado_header = "`xtabond2_ado_header'"
export delimited using "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/stata_diagnostics.csv", replace
restore

parmest, saving("artifacts/parity/xtabond2/specs/system_gmm_variable_missing/stata_params.dta", replace)
use "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/stata_params.dta", clear
export delimited using "artifacts/parity/xtabond2/specs/system_gmm_variable_missing/stata_params.csv", replace
